version: '3.8'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Your_Strong_Password_Here"  # Cambia esto!
    ports:
      - "1433:1433"
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P Your_Strong_Password_Here -Q \"SELECT 1\""]
      interval: 10s
      timeout: 10s
      retries: 10

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: backend
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "5000:5000"
    environment:
      # Ejemplo de variables de entorno para conectar con la base de datos SQL Server
      SQL_SERVER_HOST: db
      SQL_SERVER_PORT: 1433
      SQL_SERVER_USER: sa
      SQL_SERVER_PASSWORD: "Your_Strong_Password_Here"
    networks:
      - app-network
    restart: always

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: frontend
    depends_on:
      backend:
        condition: service_started
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: "http://backend:5000"
    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver: bridge